# Loops

Iremos aprender dois tipos de loops: while e for.

## while loops

Sua sintaxe resume-se em while (condição)// corpo do loop// end:

In [1]:
n = 0
while n<10
    n += 1 # Para cada iteracao, n aumenta em uma unidade e depois printamos
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
amigos=["Ted", "Robyn", "Barney", "Lilly", "Marshall"]

i=1
while i <= length(amigos)
    amigo=amigos[i]
    println("Olá $amigo, é ótimo te ver!")
    i+=1
end

Olá Ted, é ótimo te ver!
Olá Robyn, é ótimo te ver!
Olá Barney, é ótimo te ver!
Olá Lilly, é ótimo te ver!
Olá Marshall, é ótimo te ver!


## for loops

Loops do tipo for possuem sintaxe for *var* in *iteratividade do loop*// *corpo do loop*// end

É possível usarmos um for loop para obtermos os mesmos resultados anteriores:

In [3]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
amigos=["Ted", "Robyn", "Barney", "Lilly", "Marshall"]

for amigo in amigos
    println("Olá $amigo, é ótimo te ver!")
end

Olá Ted, é ótimo te ver!
Olá Robyn, é ótimo te ver!
Olá Barney, é ótimo te ver!
Olá Lilly, é ótimo te ver!
Olá Marshall, é ótimo te ver!


É possível substituirmos *in* por = ou `\in`

In [7]:
for n=1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [8]:
for n ∈ 1:10 
    println(n)
end

1
2
3
4
5
6
7
8
9
10


Para o próximo exemplo, iremos usar um for loop para criar uma tabela em que cada valor é a soma do índice de sua linha e coluna.

Primeiro, comecemos com uma matriz de zeros:

In [11]:
m,n=5,5

A = zeros(m,n)

for i in 1:m 
    for j in 1:n
        A[i,j]=i+j
    end
end

A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Podemos criar a matriz acima de uma maneira ainda mais concisa ao definirmos várias variáveis num for loop:

In [17]:
B=zeros(m,n)

for i in 1:m, j in 1:n 
    B[i,j]=i+j
end

B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

Existe uma maneira diferente de fazermos isso: através de um *array comprehension*: 

In [15]:
C=[i+j for i in 1:m, j in 1:n]

C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

Podemos combinar tudo numa coisa só: num for loop, iremos definir uma matriz (igual às anteriores) que aumenta de tamanho de acordo com cada iteração usando um *array comprehension*:

In [19]:
for n in 1:10 
    A=[i+j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20